######tile_extract_job-00196.pbs
#PBS -S /bin/bash
#PBS -l select=1:ncpus=16:model=san
#PBS -l walltime=00:60:00
#PBS -q normal
#PBS -j oe
#PBS -m abe
#PBS -M cnh@mit.edu
module load python/2.7.10
cd /home4/cnhill1/projects/get_alll_llc/python/mitgcm_llc_4320/get_subtil_py
export LLC_TEXTRACT_TNO=299
python simple_extract_looping_driver.py 1365120,1365409,144 &
python simple_extract_looping_driver.py 1365552,1365841,144 &
wait
